package ApiQuickOrder.models;
// Generated 8 may 2023 19:23:56 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;

/**
 * OrderLine generated by hbm2java
 */
@Entity
@Table(name = "orderLine", catalog = "QuickOrder")
public class OrderLine implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private OrderLineId id;
	private Order order;
	private Product product;
	private Integer qty;
	private Double price;
	private Integer unitPrice;

	public OrderLine() {
	}

	public OrderLine(OrderLineId id, Order order, Product product) {
		this.id = id;
		this.order = order;
		this.product = product;
	}

	public OrderLine(OrderLineId id, Order order, Product product, Integer qty, Double price, Integer unitPrice) {
		this.id = id;
		this.order = order;
		this.product = product;
		this.qty = qty;
		this.price = price;
		this.unitPrice = unitPrice;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "orderId", column = @Column(name = "order_id", nullable = false)) })
	public OrderLineId getId() {
		return this.id;
	}

	public void setId(OrderLineId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false, insertable = false, updatable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "qty")
	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	@Column(name = "price")
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "unitPrice")
	public Integer getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(Integer unitPrice) {
		this.unitPrice = unitPrice;
	}

}
