package ApiQuickOrder.models;
// Generated 8 may 2023 19:23:56 by Hibernate Tools 4.3.6.Final


import jakarta.persistence.*;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "QuickOrder")
public class Order implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private Address address;
	private Raider raider;
	private Restaurant restaurant;
	private User user;
	private Integer price;
	private Date deliveryTime;
	private Integer discount;
	private Set<OrderLine> orderLines = new HashSet<OrderLine>(0);

	public Order() {
	}

	public Order(Restaurant restaurant, User user) {
		this.restaurant = restaurant;
		this.user = user;
	}

	public Order(Address address, Raider raider, Restaurant restaurant, User user, Integer price, Date deliveryTime,
			Integer discount, Set<OrderLine> orderLines) {
		this.address = address;
		this.raider = raider;
		this.restaurant = restaurant;
		this.user = user;
		this.price = price;
		this.deliveryTime = deliveryTime;
		this.discount = discount;
		this.orderLines = orderLines;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "delivery_address_id")
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "raider_id")
	public Raider getRaider() {
		return this.raider;
	}

	public void setRaider(Raider raider) {
		this.raider = raider;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "restaurant_id", nullable = false)
	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "price")
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "delivery_time", length = 10)
	public Date getDeliveryTime() {
		return this.deliveryTime;
	}

	public void setDeliveryTime(Date deliveryTime) {
		this.deliveryTime = deliveryTime;
	}

	@Column(name = "discount")
	public Integer getDiscount() {
		return this.discount;
	}

	public void setDiscount(Integer discount) {
		this.discount = discount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set<OrderLine> getOrderLines() {
		return this.orderLines;
	}

	public void setOrderLines(Set<OrderLine> orderLines) {
		this.orderLines = orderLines;
	}

}
