package ApiQuickOrder.models;
// Generated 8 may 2023 19:23:56 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * OrderLineId generated by hbm2java
 */
@Embeddable
public class OrderLineId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private int orderId;

	public OrderLineId() {
	}

	public OrderLineId(int id, int orderId) {
		this.id = id;
		this.orderId = orderId;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "order_id", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderLineId))
			return false;
		OrderLineId castOther = (OrderLineId) other;

		return (this.getId() == castOther.getId()) && (this.getOrderId() == castOther.getOrderId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getOrderId();
		return result;
	}

}
