package ApiQuickOrder.models;
// Generated 8 may 2023 19:23:56 by Hibernate Tools 4.3.6.Final


import jakarta.persistence.*;

import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "QuickOrder")
public class Product implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private Restaurant restaurant;
	private String name;
	private String photo;
	private String description;
	private Integer price;
	private Integer stock;
	private Set<OrderLine> orderLines = new HashSet<OrderLine>(0);

	public Product() {
	}

	public Product(Restaurant restaurant, String name, String photo, String description, Integer price, Integer stock,
			Set<OrderLine> orderLines) {
		this.restaurant = restaurant;
		this.name = name;
		this.photo = photo;
		this.description = description;
		this.price = price;
		this.stock = stock;
		this.orderLines = orderLines;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "restaurant_id")
	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "photo", length = 50)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "price")
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	@Column(name = "stock")
	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<OrderLine> getOrderLines() {
		return this.orderLines;
	}

	public void setOrderLines(Set<OrderLine> orderLines) {
		this.orderLines = orderLines;
	}

}
