package ApiQuickOrder.models;
// Generated 22 may 2023 16:45:41 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Ratings generated by hbm2java
 */
@Entity
@Table(name = "ratings", catalog = "quick_order")
public class Ratings implements java.io.Serializable {

	private RatingsId id;
	private Double rating;

	public Ratings() {
	}

	public Ratings(RatingsId id) {
		this.id = id;
	}

	public Ratings(RatingsId id, Double rating) {
		this.id = id;
		this.rating = rating;
	}

	public Ratings(Double rating){
		this.rating = rating;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "restaurantId", column = @Column(name = "restaurant_id", nullable = false)) })
	public RatingsId getId() {
		return this.id;
	}

	public void setId(RatingsId id) {
		this.id = id;
	}

	@Column(name = "rating")
	public Double getRating() {
		return this.rating;
	}

	public void setRating(Double rating) {
		this.rating = rating;
	}

}
