package ApiQuickOrder.models;
// Generated 17 may 2023 16:31:47 by Hibernate Tools 4.3.6.Final


import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;

/**
 * Restaurant generated by hbm2java
 */
@Entity
@Table(name = "restaurant", catalog = "quick_order", uniqueConstraints = @UniqueConstraint(columnNames = "nif"))
public class Restaurant implements java.io.Serializable {

	private Integer id;
	private String name;
	private String nif;
	private String password;
	private String photo;
	private String city;
	private String direction;
	private Integer deliveryTime;
	private Integer deliveryPrice;
	private double rating;
	@JsonIgnore
	private Set<Order> orders = new HashSet<>(0);
	private Set<Product> products = new HashSet<>(0);
    private Set<Tags> tags = new HashSet<>(0);

	public Restaurant() {
	}

	public Restaurant(String name, String nif, String password, String photo, String city, String direction, Set<Order> orders,
					  Set<Product> products, Integer deliveryPrice, Integer deliveryTime, Set<Tags> tags, double rating) {
		this.name = name;
		this.nif = nif;
		this.password = password;
		this.photo = photo;
		this.city = city;
		this.direction = direction;
		this.orders = orders;
		this.products = products;
		this.deliveryPrice = deliveryPrice;
		this.deliveryTime = deliveryTime;
        this.tags = tags;
		this.rating = rating;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "nif", unique = true, length = 9)
	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	@Column(name = "password", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "photo", length = 50)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "city", length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "direction", length = 100)
	public String getDirection() {
		return this.direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "restaurant")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "restaurant")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	@Column(name = "delivery_time")
	public Integer getDeliveryTime() {
		return this.deliveryTime;
	}

	public void setDeliveryTime(Integer deliveryTime) {
		this.deliveryTime = deliveryTime;
	}

	@Column(name = "delivery_price")
	public Integer getDeliveryPrice() {
		return this.deliveryPrice;
	}

	public void setDeliveryPrice(Integer deliveryPrice) {
		this.deliveryPrice = deliveryPrice;
	}

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "restaurant")
    public Set<Tags> getTags() {
        return this.tags;
    }

    public void setTags(Set<Tags> tags) {
        this.tags = tags;
    }

	@Column(name = "rating")
	public double getRating() {
		return rating;
	}

	public void setRating(double rating) {
		this.rating = rating;
	}
}
